
services:
  api:
    build:
      context: ./APILindi
      dockerfile: Dockerfile
    ports:
      - "5000:80"
   
    networks:
      - app-network

  ui:
    build:
      context: ./UILindi/codepulse
      dockerfile: Dockerfile
    ports:
      - "4200:80"
    networks:
      - app-network

networks:
  app-network:
