
services:
  api:
    build:
      context: ./APILindi/TestiCodePulse
      dockerfile: Dockerfile
    ports:
      - "7112:80"
   
    networks:
      - app-network

  ui:
    build:
      context: ./UILindi/codepulse
      dockerfile: Dockerfile
    ports:
      - "4200:80"
    networks:
      - app-network

networks:
  app-network:
