### STAGE 1: Build ###
FROM node:alpine as builder

# Set the working directory inside the container
WORKDIR /ng-app

# Copy the package.json and package-lock.json files
COPY package.json package-lock.json ./

# Install dependencies and cache them
RUN npm install && npm install -g @angular/cli


# Copy the rest of the project files
COPY . .

# Build the Angular app in production mode
RUN ng build --configuration production



### STAGE 2: Setup ###
FROM nginx:alpine

# Copy our default nginx config
COPY nginx.conf /etc/nginx/conf.d/default.conf

# Remove default nginx website
RUN rm -rf /usr/share/nginx/html/*

# Copy the built Angular app to the nginx web root directory
COPY --from=builder /ng-app/dist/codepulse /usr/share/nginx/html

RUN chmod -R 755 /usr/share/nginx/html
# Expose port 80
EXPOSE 80

# Start nginx
CMD ["nginx", "-g", "daemon off;"]
