# Stage 1: Install dependencies and build the Angular app
FROM node:latest as build

# Set the working directory
WORKDIR /app

# Copy the Angular project files
COPY . .

RUN npm install -g @angular/cli

# Install dependencies
RUN npm install

# Build the Angular app for production
RUN npm run build

# Stage 2: Serve the Angular app with nginx
FROM nginx:alpine

# Copy the built Angular app to the nginx web root directory
COPY --from=build /app/dist/UILindi /usr/share/nginx/html

# Expose port 80
EXPOSE 80

# Start nginx
CMD ["nginx", "-g", "daemon off;"]
